
reso = [[256, 256, 256], [512, 512, 512]]
eval_every_iter = 10000
upsamp_every = 38400
lr_sigma = 3e1
lr_sh = 1e-2
lambda_tv = 1e-5
lambda_tv_sh = 1e-3
log_depth_map = True
n_eval_test = 3

background_nlayers = 64
background_reso = 1024


final_render_eval = True

dtu_no_mask = True