nokernel = True
renderer_backend = "plane"
geometry_init = "random"
reso = [[128,128,128]]
init_sigma = 0.01
nosphereinit = True

upsamp_every = 1e10

# lr_sigma = 1e-2
# lr_sigma_final = 1e-4 
# lr_geo = 3e1
lr_sh = 1e-2
lambda_tv = 0
lambda_tv_sh = 0

n_iters = 100000
print_every = 1
eval_every_iter = 5000
n_eval = 1
load_ckpt = False
log_depth_map = True

