nokernel = True
surface_type = 'sdf'
reso = [[64,64,64]]
init_sigma = 0.01
surface_init = "sphere"
nosphereinit = True

upsamp_every = 1e10

# lr_sigma = 1e-2
# lr_sigma_final = 1e-4 
# lr_geo = 1e-2
# lr_geo_final = 1e-4 
# lr_geo = 3e1
lr_sh = 1e-2
lambda_tv = 0
lambda_tv_sh = 0

n_iters = 100
print_every = 1
eval_every_iter = 20
save_every = 1000
n_eval = 1
load_ckpt = False
log_depth_map = True

