nokernel = False
# renderer_backend = 'surface'
renderer_backend = 'surf_trav'
step_size = 0.5
sigma_thresh = 1e-8
thresh_type = 'alpha'
alpha_upsample_thresh = 1e-8
near_clip = 0.

surface_type = 'sdf'
reso = [[512,512,512]]
init_sigma = 0.01
nosphereinit = True

### learning rates ###
img_lambda_l1_ratio = 1


lr_alpha = 0.1
lr_alpha_final = 1e-2
lr_alpha_delay_mult = 1e-2
lr_alpha_delay_steps = 25000
lr_alpha_decay_steps = 50000

lr_surface = 1e-2
lr_surface_final = 1e-5
lr_surface_delay_mult = 1e-2
lr_surface_delay_steps = 25000
lr_surface_decay_steps = 50000

lr_sh_surf = 1e-3
lr_sh_surf_decay_steps = 50000
lr_sh_surf_delay_mult = 1
lr_sh_surf_delay_steps = 0
lr_sh_surf_final = 1e-3

### NeRF Init ###
load_pretrain_density_sh = "/home/tw554/plenoxels/opt/ckpt/nerf/lego"
no_surface_init_iters = 0
alpha_lv_sets = 50
surf_init_alpha_rescale = 0.01
surface_init_reset_alpha = False

### Regularization ###
lambda_tv_alpha = 1e-05
lambda_tv_sh = 0
# lambda_tv_surface = 1
# tv_surface_sparsity = 0.1
# lambda_udf_var_loss = 1e-2
# lambda_density_lap_loss = 1e-2
surf_normal_loss_lambda_type = 'const'
lambda_normal_loss = 0.01
# lambda_normal_loss_final = 0
# lambda_normal_loss_delay_steps = 25000
# lambda_normal_loss_decay_steps = 50000
norm_surface_sparsity = 0.1
no_surf_norm_con_check = True
surf_norm_reg_ignore_empty = False
surf_norm_reg_l1 = True
# lambda_surf_sign_loss = 1e-2

lambda_sparsity = 0
lambda_sparsify_alpha = 0
lambda_sparsify_surf = 0
sparsify_surf_decrease = True
sparsify_surf_thresh = 0.15
alpha_sparsify_bound = 0
surf_sparsify_bound = -0.1
alpha_surf_sparsify_sparsity = 0.1
delay_sparsify_surf = 25000

lambda_l_dist = 0.
no_fake_sample_l_dist = False

### Fake Sample ###
surf_fake_sample = True
# trainable_fake_sample_std = True
# lr_fake_sample_std_delay_steps = 25000
# lr_fake_sample_std_delay_mult = 1
# lr_fake_sample_std_decay_steps = 50000
# lr_fake_sample_std = 0.01
# lr_fake_sample_std_final = 0.0001
# lambda_fake_sample_std_l1 = 0.001
# lambda_fake_sample_std_l2 = 0.001
limited_fake_sample = True
fake_sample_std = 1
fake_sample_std_final = 0.01
fake_sample_std_decay_steps = 50000

### Logging ###
n_iters = 50000
print_every = 100
eval_every_iter = 10000
# extract_mesh_every = 10000
# mesh_sigma_thresh = None
save_every = -1
n_eval_test = 3
n_eval_train = 0
load_ckpt = False
log_depth_map = True
log_normal_map = True
log_alpha_map = False
log_mse_image = False
save_all_ckpt = False
no_surface_init_debug_ckpt = False
tune_mode = False
log_depth_map_use_thresh = -10

eval_cf = True
surf_eval_n_sample = 3






