nokernel = True
surface_type = 'udf'
reso = [[16,16,16]]
init_sigma = 0.01
surface_init = 'single_lv_multi_sphere'
# nosphereinit = True

upsamp_every = 1e10

### learning rates ###
# lr_sigma = 1e-1
# lr_sigma_final = 1e-4 
lr_surface = 5e-1
# lr_surface_final = 1e-1
# lr_surface = 3e1
lr_sh = 1e-2

### regularization ###
lambda_tv = 0
lambda_tv_sh = 0
lambda_tv_surface = 0
lambda_udf_var_loss = 0
# lambda_tv = 1e-3
# lambda_tv_sh = 1e-3
# lambda_tv_surface = 1e-3
# lambda_udf_var_loss = 1e-4
# tv_surface_sparsity = 0.1

n_iters = 25000
print_every = 10
eval_every_iter = 1000
save_every = 5000
n_eval_test = 1
n_eval_train = 2
load_ckpt = False
log_depth_map = True 

