nokernel = True
surface_type = 'udf'
reso = [[8,8,8]]
init_sigma = 0.01
surface_init = 'sphere'
nosphereinit = True

upsamp_every = 1e10

# lr_sigma = 1e-2
# lr_sigma_final = 1e-4 
# lr_surface = 1e-2
# lr_surface_final = 1e-4 
# lr_surface = 3e1
lr_sh = 1e-2
lambda_tv = 0
lambda_tv_sh = 0

n_iters = 100
print_every = 10
eval_every_iter = 100
save_every = 5000
n_eval = 1
load_ckpt = False
log_depth_map = True 

