nokernel = True
surface_type = 'udf'
reso = [[256,256,256]]
init_sigma = 0.01
surface_init = 'sphere'
# nosphereinit = True

upsamp_every = 1e10

# lr_sigma = 1e-2
# lr_sigma_final = 1e-4 
lr_surface = 1e-1
# lr_surface_final = 1e-1
# lr_surface = 3e1
lr_sh = 1e-2
lambda_tv = 1e-3
lambda_tv_sh = 1e-3
lambda_tv_surface = 1e-3
lambda_udf_var_loss = 1e-4
tv_surface_sparsity = 0.1

n_iters = 50000
print_every = 10
eval_every_iter = 5000
save_every = 5000
n_eval_test = 2
n_eval_train = 0
load_ckpt = False
log_depth_map = True 

