nokernel = True
surface_type = 'udf'
reso = [[256,256,256]]
init_sigma = 0.01
surface_init = 'sphere'
nosphereinit = True

upsamp_every = 1e10

# lr_sigma = 1e-2
# lr_sigma_final = 1e-4 
# lr_surface = 1e-1
# lr_surface_final = 1e-1
# lr_surface = 3e1
lr_sh = 1e-2
lambda_tv = 0
lambda_tv_sh = 0
# lambda_tv_surface = 1e-4
lambda_udf_var_loss = 1e-3
tv_surface_sparsity = 0.1

n_iters = 50000
print_every = 10
eval_every_iter = 5000
save_every = 5000
n_eval = 1
load_ckpt = True
log_depth_map = True 

